# Generated by Django 3.0.6 on 2021-03-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210315_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='toppings',
            field=models.ManyToManyField(through='app1.PizzaOrderTops', to='app1.Topping'),
        ),
        migrations.AlterField(
            model_name='pizzaordertops',
            name='pizza_top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Topping'),
        ),
        migrations.AlterField(
            model_name='pizzatops',
            name='pizza_size',
            field=models.CharField(choices=[(1, 'small'), (2, 'medium'), (3, 'big')], default='2', max_length=1),
        ),
    ]
